### PR TITLE
Upgrade base image to debian:bullseye

### PR DESCRIPTION
**Pull request by notogawa**

### CODE REVIEW

**Comment by notogawa** [comment]
@eldesh @ishiy1993 I'll require approval from all reviewers.

**Review by ishiy1993 — APPROVED** [review]
LGTM

In my machine, `docker build` succseeds and gcc works.

**Comment by Terminus-IMRC** [comment]
@notogawa Can you add me to the reviewers?
Since GCC 10 is the default for Debian bullseye, the alternatives should be kept as is, though I'm not confident that the host compiler can be switched in place for each `ct-ng build`.

**Comment by Terminus-IMRC** [comment]
How about [idein/cross-rpi:bullseye-based-2/Dockerfile](https://github.com/Idein/docker-cross-rpi/blob/bullseye-based-2/Dockerfile)? It now builds each target in a separate stage, so we can build all the images by e.g.:
```bash
$ for tag in buster buster-slim bullseye-slim bullseye-slim; do
>     for target in base builder armv6 armv7 armv8 aarch64; do
>         docker build --build-arg DEBIAN_IMAGE_TAG=$tag --target $target --tag idein/cross-rpi:$tag-$target .
>     done
>     docker build --build-arg DEBIAN_IMAGE_TAG=$tag --tag idein/cross-rpi:$tag .
> done
```
I confirmed this works at least for `buster-slim` and `bullseye-slim`.

**Comment by notogawa** [comment]
Should we keep "All in One" image ?

I think about building image targetwise [like this](https://github.com/Idein/docker-cross-rpi/tree/targetwise-images).

**Comment by Terminus-IMRC** [comment]
Yes, on almost all applications the full image is not needed.
However, we need the one when building a package for each Raspberry Pi version in a container run, or when packing 32-bit and 64-bit binaries into a package (some VideoCore libraries only support 32-bit binaries due to pointer size for now, and AArch64 supports executing 32-bit binary if the system has 32-bit libc).

Accordingly, the new Dockerfile of mine is made to generate not only the full image `cross-rpi:bullseye` but also per-target images `cross-rpi:bullseye-armv6`, `cross-rpi:bullseye-armv7`, `cross-rpi:bullseye-armv8`, and `cross-rpi:bullseye-aarch64`.
Observe the `--tag` argument in building the intermediate stages, which I said is impossible in the last meeting, but it turned out to be possible (refer to the Slack thread). I'm sorry for the misunderstanding.

**Comment by notogawa** [comment]
ok. I'll close this PR. plz create new PR based bullseye-based-2 branch.

**Comment by Terminus-IMRC** [comment]
Thanks. Do you think the `base` tag should be available on the Docker Hub or not?

**Comment by notogawa** [comment]
required

**Pull request closed without merging**
